import './style.css';
import { BOARD, GameSimulation, Hole, MAX_SHOTS, Vec, dailySeed, makeCourse, predictedPoints } from './game';

type Saved = { best: number | null; completed: string[]; sound: boolean };
const app = document.querySelector<HTMLDivElement>('#app')!;
const dateText = new Intl.DateTimeFormat('en-GB', { weekday: 'short', month: 'short', day: 'numeric', timeZone: 'UTC' }).format(new Date());
let demo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let stopGame = () => {};
const key = () => `${demo ? 'demo:' : 'pinpoint:'}daily-v1`;
const load = (): Saved => { try { return JSON.parse(localStorage.getItem(key()) || '{"best":null,"completed":[],"sound":false}'); } catch { return { best: null, completed: [], sound: false }; } };
const save = (value: Saved) => localStorage.setItem(key(), JSON.stringify(value));

function link(path: string, label: string) { return `<a href="${path}" data-route>${label}</a>`; }
function shell(content: string) {
  app.innerHTML = `<a class="skip" href="#main">Skip to game</a><header><a class="wordmark" href="/" data-route aria-label="Pinpoint Daily home"><span>PIN</span>POINT <b>DAILY</b></a><nav aria-label="Main navigation">${link('/demo', 'Demo')}${link('/#how', 'How it works')}${link('/privacy', 'Privacy')}</nav></header><main id="main" tabindex="-1">${content}</main><footer><span>One shared tabletop course each day.</span>${link('/privacy', 'Privacy')}${link('/terms', 'Terms')}<span>Built by Param Factory · build 1.0.0</span><span>Course art uses original generated imagery.</span></footer><div class="sr-only" aria-live="polite" id="announcer"></div>`;
  wireLinks();
}
function policy(type: 'privacy' | 'terms') {
  stopGame(); stopGame = () => {};
  const privacy = type === 'privacy'; document.title = `${privacy ? 'Privacy' : 'Terms'} — Pinpoint Daily`;
  shell(`<section class="legal"><p class="eyebrow">${privacy ? 'PRIVACY' : 'TERMS'}</p><h1>${privacy ? 'Your scores stay on this device' : 'Rules for playing Pinpoint Daily'}</h1><p>${privacy ? 'Pinpoint Daily stores your daily best score and settings in this browser only.' : 'Pinpoint Daily is a free game for general audiences.'}</p><h2>${privacy ? 'What is stored' : 'Use of the game'}</h2><p>${privacy ? 'The current run, completed dates, sound setting, and best score use local browser storage. No account is required. We do not send game data to a server.' : 'Play fairly, do not interfere with the site, and use the game at your own discretion.'}</p><h2>${privacy ? 'How to remove it' : 'Availability'}</h2><p>${privacy ? 'Use “Clear local score” on the game screen, or clear this site’s browser data. Demo data has a separate storage key and is discarded when reset.' : 'The course and its local storage are provided as-is and may change with future releases.'}</p><p><a href="/" data-route>Return to today’s course</a></p></section>`);
}
function home() {
  stopGame(); stopGame = () => {};
  document.title = demo ? 'Demo — Pinpoint Daily' : 'Pinpoint Daily — Play a daily three-hole course';
  const banner = demo ? `<aside class="demo-banner" role="status"><strong>Demo — sample data, nothing is saved</strong><button id="reset-demo">Reset demo</button><button id="start-real">Start for real</button></aside>` : '';
  shell(`${banner}<section class="intro"><div><p class="eyebrow">TODAY’S SHARED COURSE · ${dateText.toUpperCase()}</p><h1>Play today’s three-hole course</h1><p class="lede">For players who want a fair two-minute physics puzzle, not another word game.</p><div class="actions"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span>Opens a practice course with nothing saved.</span></div><ul class="facts"><li>Free to play</li><li>Five shots per hole</li><li>Scores stay on this device</li></ul></div><img src="/hero-blueprint.webp" width="1200" height="800" fetchpriority="high" decoding="async" alt="A tabletop golf course drawn on a navy blueprint sheet." /></section><section class="play-section" aria-labelledby="course-heading"><div class="section-title"><div><p class="eyebrow">LIVE COURSE</p><h2 id="course-heading">Aim, check the dotted path, then shoot</h2></div><p>Drag away from the ball to set aim and power.</p></div><div id="game-root"></div></section><section class="how" id="how"><p class="eyebrow">HOW IT WORKS</p><h2>Play the daily course in three steps</h2><ol><li><b>Read the board.</b> Wind, walls, and the moving bumper are visible.</li><li><b>Drag a shot.</b> The dotted path previews bounces before release.</li><li><b>Finish three holes.</b> Each hole allows five shots.</li></ol></section><section class="privacy-note"><h2>What this game does not do</h2><p>It does not track you, sell scores, or use a public leaderboard. Your best score is device-local.</p></section>`);
  mountGame(document.querySelector('#game-root')!);
  if (demo) { document.querySelector('#reset-demo')?.addEventListener('click', () => { localStorage.removeItem(key()); home(); }); document.querySelector('#start-real')?.addEventListener('click', () => { demo = false; history.pushState({}, '', '/'); home(); }); }
}
function route() { const path = location.pathname; if (path === '/privacy') policy('privacy'); else if (path === '/terms') policy('terms'); else home(); }
function wireLinks() { document.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach(a => a.addEventListener('click', e => { if (e.metaKey || e.ctrlKey) return; e.preventDefault(); history.pushState({}, '', a.href); route(); document.querySelector('h1')?.focus(); })); }
window.addEventListener('popstate', route);

function mountGame(root: Element) {
  const canvas = document.createElement('canvas'); canvas.width = BOARD.w * devicePixelRatio; canvas.height = BOARD.h * devicePixelRatio; canvas.style.aspectRatio = `${BOARD.w}/${BOARD.h}`; canvas.setAttribute('aria-label', 'Interactive tabletop golf course'); canvas.tabIndex = 0;
  const ctx = canvas.getContext('2d')!; ctx.scale(devicePixelRatio, devicePixelRatio);
  root.innerHTML = `<div class="game-wrap"><div class="score-strip"><span id="hole-label">Hole 1 of 3</span><span id="shot-label">Shots: 0 / ${MAX_SHOTS}</span><span id="wind-label"></span><button id="pause">Pause</button></div></div><div class="game-controls"><button id="left" aria-label="Aim left">← Aim</button><button id="right" aria-label="Aim right">Aim →</button><button id="less">Less power</button><button id="more">More power</button><button class="shoot" id="shoot">Shoot</button><button id="reset-hole">Reset hole</button><button id="sound">Sound off</button></div><div class="game-status" id="game-status" aria-live="polite">Drag from the ball, or use arrow keys and Enter.</div><div class="results" id="results" hidden></div><button class="clear-score" id="clear-score">Clear local score</button>`;
  root.querySelector('.game-wrap')!.append(canvas);
  const holes = makeCourse(dailySeed()); let holeIndex = 0, shots = 0, total = 0, angle = -.4, power = 95, drag: Vec | null = null, paused = false; let sim = new GameSimulation(holes[0]); let last = performance.now(), accumulator = 0; const stored = load();
  const status = root.querySelector<HTMLElement>('#game-status')!, result = root.querySelector<HTMLElement>('#results')!, holeLabel = root.querySelector<HTMLElement>('#hole-label')!, shotLabel = root.querySelector<HTMLElement>('#shot-label')!, windLabel = root.querySelector<HTMLElement>('#wind-label')!;
  const coords = (e: PointerEvent): Vec => { const box = canvas.getBoundingClientRect(); return { x: (e.clientX - box.left) * BOARD.w / box.width, y: (e.clientY - box.top) * BOARD.h / box.height }; };
  const fire = (aim: Vec) => { if (!sim.shoot(aim)) return; shots++; total++; shotLabel.textContent = `Shots: ${shots} / ${MAX_SHOTS}`; status.textContent = 'Ball rolling. Watch the bounce.'; };
  canvas.addEventListener('pointerdown', e => { if (sim.moving || paused) return; canvas.setPointerCapture(e.pointerId); drag = coords(e); });
  canvas.addEventListener('pointermove', e => { if (drag) { const point = coords(e); drag = { x: sim.ball.x - point.x, y: sim.ball.y - point.y }; } });
  canvas.addEventListener('pointerup', () => { if (drag) { fire(drag); drag = null; } });
  const keyboard = (e: KeyboardEvent) => { if (e.key === 'ArrowLeft') { angle -= .12; e.preventDefault(); } if (e.key === 'ArrowRight') { angle += .12; e.preventDefault(); } if (e.key === 'ArrowUp') { power = Math.min(180, power + 10); e.preventDefault(); } if (e.key === 'ArrowDown') { power = Math.max(30, power - 10); e.preventDefault(); } if (e.key === 'Enter' || e.key === ' ') { fire({ x: Math.cos(angle) * power, y: Math.sin(angle) * power }); e.preventDefault(); } if (e.key.toLowerCase() === 'r') reset(); if (e.key === 'Escape') togglePause(); };
  window.addEventListener('keydown', keyboard);
  const reset = () => { sim.reset(); status.textContent = 'Hole reset. Your used shots remain counted.'; };
  const togglePause = () => { paused = !paused; root.querySelector<HTMLButtonElement>('#pause')!.textContent = paused ? 'Resume' : 'Pause'; status.textContent = paused ? 'Game paused.' : 'Game resumed.'; };
  root.querySelector('#reset-hole')?.addEventListener('click', reset); root.querySelector('#pause')?.addEventListener('click', togglePause); root.querySelector('#left')?.addEventListener('click', () => angle -= .12); root.querySelector('#right')?.addEventListener('click', () => angle += .12); root.querySelector('#less')?.addEventListener('click', () => power = Math.max(30, power - 10)); root.querySelector('#more')?.addEventListener('click', () => power = Math.min(180, power + 10)); root.querySelector('#shoot')?.addEventListener('click', () => fire({ x: Math.cos(angle) * power, y: Math.sin(angle) * power })); root.querySelector('#sound')?.addEventListener('click', () => { const next = load(); next.sound = !next.sound; save(next); root.querySelector<HTMLButtonElement>('#sound')!.textContent = next.sound ? 'Sound on' : 'Sound off'; }); root.querySelector('#clear-score')?.addEventListener('click', () => { localStorage.removeItem(key()); status.textContent = 'Local score cleared.'; });
  function nextHole(cup: boolean) { if (holeIndex === 2) { finish(); return; } holeIndex++; shots = 0; sim = new GameSimulation(holes[holeIndex]); holeLabel.textContent = `Hole ${holeIndex + 1} of 3`; shotLabel.textContent = `Shots: 0 / ${MAX_SHOTS}`; status.textContent = cup ? 'In the cup. Next hole.' : 'Five shots used. Next hole.'; }
  function finish() { const next = load(); if (next.best === null || total < next.best) next.best = total; if (!next.completed.includes(new Date().toISOString().slice(0,10))) next.completed.push(new Date().toISOString().slice(0,10)); save(next); result.hidden = false; result.innerHTML = `<h3>Course complete</h3><p>You finished in <strong>${total} shots</strong>. ${next.best === total ? 'That is your local best.' : `Local best: ${next.best} shots.`}</p><button id="play-again">Play again</button>`; result.querySelector('#play-again')?.addEventListener('click', () => { result.hidden = true; holeIndex = 0; shots = 0; total = 0; sim = new GameSimulation(holes[0]); holeLabel.textContent = 'Hole 1 of 3'; shotLabel.textContent = `Shots: 0 / ${MAX_SHOTS}`; status.textContent = 'New run. Read the path before shooting.'; }); }
  function draw() { const hole = holes[holeIndex]; ctx.clearRect(0, 0, BOARD.w, BOARD.h); ctx.fillStyle = '#073957'; ctx.fillRect(0, 0, BOARD.w, BOARD.h); ctx.strokeStyle = 'rgba(83,214,230,.16)'; ctx.lineWidth = 1; for (let x = 0; x < BOARD.w; x += 32) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, BOARD.h); ctx.stroke(); } for (let y = 0; y < BOARD.h; y += 32) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(BOARD.w, y); ctx.stroke(); } ctx.strokeStyle = '#53d6e6'; ctx.lineWidth = 4; ctx.strokeRect(7, 7, BOARD.w - 14, BOARD.h - 14); for (const w of hole.walls) { ctx.fillStyle = '#f5edd7'; ctx.fillRect(w.x, w.y, w.w, w.h); ctx.fillStyle = '#0b5f92'; ctx.fillRect(w.x + 5, w.y + 5, w.w - 10, w.h - 10); } const bumper = sim.bumperAt(); ctx.fillStyle = '#ff715b'; ctx.beginPath(); ctx.arc(bumper.x, bumper.y, 14, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#fff9e9'; ctx.lineWidth = 2; ctx.stroke(); ctx.strokeStyle = '#f7c948'; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(hole.cup.x, hole.cup.y, BOARD.cup, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = '#f7c948'; ctx.fillRect(hole.cup.x, hole.cup.y - 45, 3, 29); ctx.beginPath(); ctx.moveTo(hole.cup.x + 3, hole.cup.y - 45); ctx.lineTo(hole.cup.x + 29, hole.cup.y - 36); ctx.lineTo(hole.cup.x + 3, hole.cup.y - 27); ctx.fill(); const aim = drag || (!sim.moving ? { x: Math.cos(angle) * power, y: Math.sin(angle) * power } : null); if (aim && !paused) { const p = predictedPoints(hole, sim.ball, aim); ctx.fillStyle = '#53d6e6'; p.forEach((point, i) => { if (i % 2 === 0) { ctx.beginPath(); ctx.arc(point.x, point.y, 2.5, 0, Math.PI * 2); ctx.fill(); } }); ctx.strokeStyle = 'rgba(83,214,230,.75)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(sim.ball.x, sim.ball.y); ctx.lineTo(sim.ball.x + aim.x, sim.ball.y + aim.y); ctx.stroke(); } ctx.fillStyle = '#fff9e9'; ctx.beginPath(); ctx.arc(sim.ball.x, sim.ball.y, BOARD.ball, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#062947'; ctx.lineWidth = 2; ctx.stroke(); windLabel.textContent = hole.wind.x || hole.wind.y ? `Wind ${hole.wind.x > 0 ? '→' : '←'} light` : 'No wind'; }
  let active = true;
  stopGame = () => { active = false; window.removeEventListener('keydown', keyboard); };
  function loop(now: number) { if (!active) return; const dt = Math.min(.1, (now - last) / 1000); last = now; if (!document.hidden && !paused) { accumulator += dt; while (accumulator >= 1 / 60) { sim.step(); accumulator -= 1 / 60; } if (sim.inCup) { sim.inCup = false; nextHole(true); } else if (!sim.moving && shots >= MAX_SHOTS) nextHole(false); } draw(); requestAnimationFrame(loop); }
  requestAnimationFrame(loop);
}
route();
